/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.thrift.registry;


public class InvalidInputException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public String what; // required
	public String why; // required
  
	public String getWhat() {
		return what;
	}
	public void setWhat(String what) {
		this.what = what;
	}
	public String getWhy() {
		return why;
	}
	public void setWhy(String why) {
		this.why = why;
	}

	
  
	public InvalidInputException(String what, String why) {
		super();
		this.what = what;
		this.why = why;
	}
	@Override
	public String toString() {
		return ""+what+" : "+why;
	}
 
}

